update danhmuc_tour set name='Anh',name_url='anh',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='1',title='Anh',keyword='Anh',description='Anh' where id=1;
update danhmuc_tour set name='Anh',name_url='anh',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='1',title='Anh',keyword='Anh',description='Anh' where id=1;
update danhmuc_tour set name='Pháp',name_url='phap',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='2',title='Pháp',keyword='Pháp',description='Pháp' where id=2;
update danhmuc_tour set name='Đức',name_url='duc',img='/mix/view/admin/Themes/kcfinder/upload/images/danhmuctour/balloon-tour-experience-with-winery-visit-in-florence-266514.jpg',position='3',title='Đức',keyword='Đức',description='Đức' where id=3;
update danhmuc_tour set name='Đức',name_url='duc',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='3',title='Đức',keyword='Đức',description='Đức' where id=3;
update danhmuc_tour set name='Italia',name_url='italia',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='4',title='Italia',keyword='Italia',description='Italia' where id=4;
update danhmuc_tour set name='Hà Lan',name_url='ha-lan',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='5',title='Hà Lan',keyword='Hà Lan',description='Hà Lan' where id=5;
update danhmuc_tour set name='Bỉ',name_url='bi',img='/mix/view/admin/Themes/kcfinder/upload/images/danhmuctour/balloon-tour-experience-with-winery-visit-in-florence-266514.jpg',position='1',title='Bỉ',keyword='Bỉ',description='Bỉ' where id=6;
update danhmuc_tour set name='Bỉ',name_url='bi',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='1',title='Bỉ',keyword='Bỉ',description='Bỉ' where id=6;
update danhmuc_tour set name='Thụy Sĩ',name_url='thuy-si',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='2',title='Thụy Sĩ',keyword='Thụy Sĩ',description='Thụy Sĩ' where id=7;
update danhmuc_tour set name='Bỉ',name_url='bi',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='6',title='Bỉ',keyword='Bỉ',description='Bỉ' where id=6;
update danhmuc_tour set name='Thụy Sĩ',name_url='thuy-si',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='7',title='Thụy Sĩ',keyword='Thụy Sĩ',description='Thụy Sĩ' where id=7;
update danhmuc_tour set name='Tây Ban Nha',name_url='tay-ban-nha',img='/chauau/view/admin/Themes/kcfinder/upload/images/danhmuctour/848166.jpg',position='8',title='Tây Ban Nha',keyword='Tây Ban Nha',description='Tây Ban Nha' where id=8;
delete from danhmuc_tour where id=9;
delete from danhmuc_tour where id=10;
delete from danhmuc_tour where id=11;
delete from danhmuc_tour where id=12;
delete from danhmuc_tour where id=13;
delete from danhmuc_tour where id=14;
delete from danhmuc_tour where id=15;
delete from danhmuc_tour where id=16;
delete from danhmuc_tour where id=17;
delete from danhmuc_tour where id=18;
delete from danhmuc_tour where id=19;
delete from danhmuc_tour where id=20;
