insert into khachsan (danhmuc_id,name,name_url,img,content,title,keyword,description) values ('1','St James Court - A Taj Hotel - London','st-james-court-a-taj-hotel-london','/chauau/view/admin/Themes/kcfinder/upload/images/khachsan/28049584.jpg','<p>
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tọa lạc ở vị tr&iacute; đẹp của Victoria v&agrave; Westminster, St James Court - A Taj Hotel - London hưởng được rất nhiều lợi thế trong kinh doanh, mua sắm, nh&agrave; h&agrave;ng trung t&acirc;m của London. Chỉ c&aacute;ch những hoạt động th&uacute; vị ở trung t&acirc;m th&agrave;nh phố khoảng 2.5 km. Với vị tr&iacute; thuận lợi, kh&aacute;ch sạn dễ d&agrave;ng tiếp cận những điểm tham quan du lịch nổi tiếng của th&agrave;nh phố.</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">St James Court - A Taj Hotel - London cũng đề xuất th&ecirc;m rất nhiều thiết bị l&agrave;m k&igrave; nghỉ của bạn ở London th&ecirc;m tiện lợi. Khi nghỉ ngơi trong kh&aacute;ch sạn tuyệt vời n&agrave;y, kh&aacute;ch c&oacute; thể tận hưởng quầy nước, dịch vụ Internet, ph&ograve;ng h&uacute;t thuốc, người vận chuyển h&agrave;nh l&yacute;, nh&agrave; h&agrave;ng.</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tất cả nơi ăn chốn ở của kh&aacute;ch đều c&oacute; trang bị tiện nghi chu đ&aacute;o để bảo đảm kh&aacute;ch c&oacute; cảm gi&aacute;c dễ chịu kh&ocirc;ng nơi n&agrave;o s&aacute;nh được. Kh&aacute;ch sạn cung cấp rất nhiều phương tiện giải tr&iacute; độc đ&aacute;o như tắm hơi, vườn, m&aacute;t xa, ph&ograve;ng thể dục. St James Court - A Taj Hotel - London l&agrave; nơi bạn c&oacute; thể dừng ch&acirc;n ở một kh&aacute;ch sạn chất lượng tại London.</span></p>
','St James Court - A Taj Hotel - London','St James Court - A Taj Hotel - London','St James Court - A Taj Hotel - London');
insert into khachsan (danhmuc_id,name,name_url,img,content,title,keyword,description) values ('1','Eiffel Capitol Hotel','eiffel-capitol-hotel','/chauau/view/admin/Themes/kcfinder/upload/images/khachsan/28049584.jpg','<p>
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
','Eiffel Capitol Hotel','Eiffel Capitol Hotel','Eiffel Capitol Hotel');
update khachsan set danhmuc_id='1',name='Eiffel Capitol Hotel',name_url='eiffel-capitol-hotel',start='3',room_type='',img='/chauau/view/admin/Themes/kcfinder/upload/images/khachsan/28049584.jpg',content='<p>
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Eiffel Capitol Hotel',keyword='Eiffel Capitol Hotel',description='Eiffel Capitol Hotel' where id=2;
update khachsan set danhmuc_id='1',danhmuc_multi='',name='Eiffel Capitol Hotel',name_url='eiffel-capitol-hotel',start='3',room_type='',img='/chauau/view/admin/Themes/kcfinder/upload/images/khachsan/28049584.jpg',content='<p>
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Eiffel Capitol Hotel',keyword='Eiffel Capitol Hotel',description='Eiffel Capitol Hotel' where id=2;
update khachsan set danhmuc_id='1',danhmuc_multi='1,2',name='Eiffel Capitol Hotel',name_url='eiffel-capitol-hotel',start='3',room_type='',img='/chauau/view/admin/Themes/kcfinder/upload/images/khachsan/28049584.jpg',content='<p>
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Nằm ở vị tr&iacute; thuận lợi trong Th&aacute;p Eiffel / Porte de Versailles, Eiffel Capitol Hotel l&agrave; một điểm l&yacute; tưởng để khởi h&agrave;nh chuyến du ngoạn của bạn ở Paris. Từ đ&acirc;y, kh&aacute;ch c&oacute; thể dễ d&agrave;ng tiếp cận được n&eacute;t đẹp sống động của th&agrave;nh phố ở mọi g&oacute;c cạnh. Kh&aacute;ch sạn hiện đại n&agrave;y nằm trong khu l&acirc;n cận với c&aacute;c địa điểm tham quan nổi tiếng của th&agrave;nh phố như Đại sứ qu&aacute;n &Uacute;c, Piscine Keller Pool, Champ de Mars.</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tại Eiffel Capitol Hotel, mọi sự cố gắng đều nhằm mục đ&iacute;ch khiến cho du kh&aacute;ch h&agrave;i l&ograve;ng. Để l&agrave;m được điều đ&oacute;, kh&aacute;ch sạn sẽ cung cấp dịch vụ v&agrave; tiện nghi tốt nhất. Lưu trữ h&agrave;nh l&yacute;, Wi-Fi ở khu vực c&ocirc;ng cộng, tủ đựng đồ c&oacute; kho&aacute;, thang m&aacute;y, quầy lễ t&acirc;n 24 giờ chỉ l&agrave; một v&agrave;i trong số những thiết bị được lắp đặt tại Eiffel Capitol Hotel ngo&agrave;i một số kh&aacute;ch sạn kh&aacute;c trong th&agrave;nh phố.&nbsp;</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">42 ph&ograve;ng trong tổng số 4 lầu mang đến cho bạn sự ấm c&uacute;ng v&agrave; dễ chịu như đang được ở nh&agrave; v&agrave; những thiết bị hiện đại như tắm bồn v&agrave; tắm hoa sen ri&ecirc;ng, tivi LCD/Plasma, m&aacute;y sấy t&oacute;c, k&eacute;t sắt, m&aacute;y lạnh. B&ecirc;n cạnh đ&oacute;, kh&aacute;ch sạn c&ograve;n gợi &yacute; cho bạn những hoạt động vui chơi giải tr&iacute; bảo đảm bạn lu&ocirc;n thấy hứng th&uacute; trong suốt k&igrave; nghỉ. Eiffel Capitol Hotel l&agrave; một sự lựa chọn th&ocirc;ng minh cho du kh&aacute;ch khi đến Paris, nơi mang lại cho họ một k&igrave; nghỉ thư gi&atilde;n v&agrave; thoải m&aacute;i.</span></p>
',title='Eiffel Capitol Hotel',keyword='Eiffel Capitol Hotel',description='Eiffel Capitol Hotel' where id=2;
update khachsan set danhmuc_id='1',danhmuc_multi='3,4,5',name='St James Court - A Taj Hotel - London',name_url='st-james-court-a-taj-hotel-london',start='5',room_type='',img='/chauau/view/admin/Themes/kcfinder/upload/images/khachsan/28049584.jpg',content='<p>
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tọa lạc ở vị tr&iacute; đẹp của Victoria v&agrave; Westminster, St James Court - A Taj Hotel - London hưởng được rất nhiều lợi thế trong kinh doanh, mua sắm, nh&agrave; h&agrave;ng trung t&acirc;m của London. Chỉ c&aacute;ch những hoạt động th&uacute; vị ở trung t&acirc;m th&agrave;nh phố khoảng 2.5 km. Với vị tr&iacute; thuận lợi, kh&aacute;ch sạn dễ d&agrave;ng tiếp cận những điểm tham quan du lịch nổi tiếng của th&agrave;nh phố.</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">St James Court - A Taj Hotel - London cũng đề xuất th&ecirc;m rất nhiều thiết bị l&agrave;m k&igrave; nghỉ của bạn ở London th&ecirc;m tiện lợi. Khi nghỉ ngơi trong kh&aacute;ch sạn tuyệt vời n&agrave;y, kh&aacute;ch c&oacute; thể tận hưởng quầy nước, dịch vụ Internet, ph&ograve;ng h&uacute;t thuốc, người vận chuyển h&agrave;nh l&yacute;, nh&agrave; h&agrave;ng.</span><br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<br style=\"margin: 0px; padding: 0px; list-style: none outside none; outline: none medium; font-size: 13px; color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif;\" />
	<span style=\"color: rgb(45, 45, 45); font-family: arial, Verdana, Helvetica, sans-serif; font-size: 13px;\">Tất cả nơi ăn chốn ở của kh&aacute;ch đều c&oacute; trang bị tiện nghi chu đ&aacute;o để bảo đảm kh&aacute;ch c&oacute; cảm gi&aacute;c dễ chịu kh&ocirc;ng nơi n&agrave;o s&aacute;nh được. Kh&aacute;ch sạn cung cấp rất nhiều phương tiện giải tr&iacute; độc đ&aacute;o như tắm hơi, vườn, m&aacute;t xa, ph&ograve;ng thể dục. St James Court - A Taj Hotel - London l&agrave; nơi bạn c&oacute; thể dừng ch&acirc;n ở một kh&aacute;ch sạn chất lượng tại London.</span></p>
',title='St James Court - A Taj Hotel - London',keyword='St James Court - A Taj Hotel - London',description='St James Court - A Taj Hotel - London' where id=1;
